schooldevops:
  prop-test:
    name: Schooldevops Test Sample
    friends: Chulsu,Dongsoo,Konan,Moana
    cutline: {A: '90', B: '80', C: '70', D: '60', F: '59'}
    cutline2:
      A: 90
      B: 80
      C: 70
      D: 60
      F: 59